name: Spell checking
on: [pull_request, push]

jobs:
  build:
    name: Spell checker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - uses: jsoref/spelling-action@master
      env:
        bucket: https://raw.githubusercontent.com/jsoref/test-test
        project: spelling-data
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
